import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useForm } from 'react-hook-form'
import { CreateUserInput } from '../schema/user.schema'
import { trpc } from '../utils/trpc'

function RegisterPage() {
  const { handleSubmit, register } = useForm<CreateUserInput>()
  const router = useRouter()

  const { mutate, error } = trpc.useMutation(['users.register-user'], {
    onSuccess: () => {
      router.push('/login')
    },
  })

  function onSubmit(values: CreateUserInput) {
    mutate(values)
  }

  return (
    <div>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form
          className="flex items-center justify-center h-screen w-full"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="card w-96 bg-base-100 shadow-xl">
          {error && error.message}
            <div className="card-body">
              <h2 className="card-title">Create an account!</h2>

              <input
                type="email"
                placeholder="jane.doe@example.com"
                className="input input-bordered w-full max-w-xs my-2"
                {...register('email')}
              />
              <input
                type="text"
                placeholder="Tom"
                className="input input-bordered w-full max-w-xs my-2"
                {...register('name')}
              />
              <button type="submit" className="btn btn-secondary">Register</button>
            </div>
          </div>
        </form>
      </main>

      <Link href="/login">Login</Link>
    </div>
  )
}

export default RegisterPage